// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Bookings
{
    public int BookingID { get; set; }

    public int? UserID { get; set; }

    public int? EventID { get; set; }

    public DateTime? BookingDate { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string ShiftType { get; set; }

    public string BookingStatus { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? AdvancePayment { get; set; }

    public decimal? RemainingPayment { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Events Event { get; set; }

    public virtual Users User { get; set; }
}