// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Bookings
{
    public int bookingId { get; set; }

    public int? userId { get; set; }

    public int? eventId { get; set; }

    public DateTime? bookingDate { get; set; }

    public DateTime? fromDate { get; set; }

    public DateTime? toDate { get; set; }

    public string shiftType { get; set; }

    public string bookingStatus { get; set; }

    public decimal? totalAmount { get; set; }

    public decimal? advancePayment { get; set; }

    public decimal? remainingPayment { get; set; }

    public string paymentStatus { get; set; }

    public DateTime? createdDate { get; set; }

    public string customerName { get; set; }

    public string phoneNumber { get; set; }

    public string alternativeNumber { get; set; }

    public string address { get; set; }

    public virtual Events _event { get; set; }

    public virtual Users user { get; set; }
    public string? dateWiseShifts { get; set; }

}