// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbOperation.Models;

public partial class Events
{
    public int eventId { get; set; }

    public string eventName { get; set; }

    public string description { get; set; }

    public int? userId { get; set; }

    public DateTime? createdDate { get; set; }

    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();

    public virtual Users user { get; set; }
}