// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DbOperation.Models;

public partial class EventContext : DbContext
{
    public EventContext(DbContextOptions<EventContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bookings> Bookings { get; set; }

    public virtual DbSet<Events> Events { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bookings>(entity =>
        {
            entity.HasKey(e => e.BookingID).HasName("PK__Bookings__73951ACD1702A52E");

            entity.Property(e => e.AdvancePayment).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.BookingDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.BookingStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FromDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RemainingPayment).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ShiftType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ToDate).HasColumnType("datetime");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Event).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.EventID)
                .HasConstraintName("FK__Bookings__EventI__5165187F");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserID)
                .HasConstraintName("FK__Bookings__UserID__5070F446");
        });

        modelBuilder.Entity<Events>(entity =>
        {
            entity.HasKey(e => e.eventId).HasName("PK__Events__2DC7BD0995EEB809");

            entity.Property(e => e.createdDate).HasColumnType("datetime");
            entity.Property(e => e.description)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.eventName)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.user).WithMany(p => p.Events)
                .HasForeignKey(d => d.userId)
                .HasConstraintName("FK__Events__userId__4BAC3F29");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.userId).HasName("PK__Users__CB9A1CFF3C57403B");

            entity.Property(e => e.createdDate).HasColumnType("datetime");
            entity.Property(e => e.email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.fullName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.passwordHash)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.phoneNumber)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.userRole)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}