// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DbOperation.Models;

public partial class EventContext : DbContext
{
    public EventContext(DbContextOptions<EventContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bookings> Bookings { get; set; }

    public virtual DbSet<Events> Events { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bookings>(entity =>
        {
            entity.HasKey(e => e.bookingId).HasName("PK__Bookings__C6D03BCDC86B459A");

            entity.Property(e => e.address).HasMaxLength(255);
            entity.Property(e => e.advancePayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.alternativeNumber).HasMaxLength(15);
            entity.Property(e => e.bookingDate).HasColumnType("datetime");
            entity.Property(e => e.bookingStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.createdDate)
                .HasDefaultValueSql("GETDATE()");
            entity.Property(e => e.customerName).HasMaxLength(255);
            entity.Property(e => e.fromDate).HasColumnType("datetime");
            entity.Property(e => e.paymentStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.phoneNumber).HasMaxLength(15);
            entity.Property(e => e.remainingPayment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.shiftType)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.toDate).HasColumnType("datetime");
            entity.Property(e => e.totalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d._event).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.eventId)
                .HasConstraintName("FK__Bookings__eventI__5629CD9C");

            entity.HasOne(d => d.user).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.userId)
                .HasConstraintName("FK__Bookings__userId__5535A963");
        });

        modelBuilder.Entity<Events>(entity =>
        {
            entity.HasKey(e => e.eventId).HasName("PK__Events__2DC7BD0995EEB809");

            entity.Property(e => e.createdDate).HasColumnType("datetime");
            entity.Property(e => e.description)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.eventName)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.user).WithMany(p => p.Events)
                .HasForeignKey(d => d.userId)
                .HasConstraintName("FK__Events__userId__4BAC3F29");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.userId).HasName("PK__Users__CB9A1CFF3C57403B");

            entity.Property(e => e.createdDate).HasColumnType("datetime");
            entity.Property(e => e.email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.fullName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.passwordHash)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.phoneNumber)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.userRole)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}